# Generated by Django 5.2.14 on 2026-05-11 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/')),
                ('author', models.CharField(default='Omkar Jagdale', max_length=100)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='BrochureLead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('downloaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-downloaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('icon', models.CharField(default='fas fa-code', help_text='FontAwesome class', max_length=50)),
                ('duration', models.CharField(default='3–6 Months', max_length=60)),
                ('description', models.TextField()),
                ('syllabus', models.TextField(help_text='Key topics, one per line')),
                ('certificate_issued', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_highlighted', models.BooleanField(default=False, help_text='Show as featured/highlighted')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('course', models.CharField(choices=[('software-development', 'Software Development'), ('data-science', 'Data Science & Analytics'), ('git-version-control', 'Git & Version Control'), ('system-architecture', 'System Architecture'), ('dev-tools-ides', 'Development Tools & IDEs'), ('cyber-security', 'Cyber Security'), ('cloud-computing', 'Cloud Computing'), ('devops', 'DevOps Engineering'), ('python', 'Python Programming'), ('fullstack', 'Full Stack Web Development'), ('dsa', 'DSA + Competitive Programming'), ('other', 'Other / Not Sure')], default='other', max_length=60)),
                ('branch', models.CharField(blank=True, choices=[('kalamboli', 'Kalamboli'), ('kamothe', 'Kamothe'), ('panvel', 'Panvel'), ('any', 'Any / Nearest')], default='any', max_length=20)),
                ('mode', models.CharField(blank=True, choices=[('online', 'Online'), ('offline', 'Offline / Classroom'), ('hybrid', 'Hybrid')], default='offline', max_length=10)),
                ('message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_contacted', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Enquiry',
                'verbose_name_plural': 'Enquiries',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PlacedStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('role', models.CharField(default='Software Developer', max_length=100)),
                ('company', models.CharField(default='SP Finance', max_length=150)),
                ('batch', models.CharField(default='2025', max_length=20)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='placed_students/')),
                ('linkedin_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('course', models.CharField(max_length=100)),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5)),
                ('review', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
